services:
  oracle:
    image: docker.arvancloud.ir/wvbirder/database-enterprise:12.2.0.1-slim
    container_name: oracle
    hostname: oracle
    ports:
      - "1521:1521"
      - "5000:5000"
    environment:
      - ORACLE_PWD=localdev
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - monitoring_network
    healthcheck:
      test:
        [
          "CMD",
          "sqlplus",
          "-S",
          "sys/localdev@localhost:1521/orclpdb1.localdomain as sysdba",
          "<",
          "/dev/null",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          memory: 2G

volumes:
  oracle_data:

networks:
  monitoring_network:
