name: MkDocs Build

on:
  schedule:
    - cron: "0 14 * * *"

  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name:
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:  
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: mkdocs gh-deploy --force
